### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tapanih** [lauriap/ot-harjoitustyo#1]
Latasin sovelluksen 27.4 klo 01:00.

Sovellus toimii hyvin ja siinä on jo kivasti ominaisuuksia. Koodi on selkeää luettavaa. Se on hyvin dokumentoitua, muuttujien nimet ovat kuvaavia ja se on myös jaettu luokkiin järkevällä tavalla.
 
Pidän tavasta, jolla käyttöliittymän koodi on organisoitu. Kaikki käytetyt elementit on määritelty heti alussa, mikä tekee koodista selkeää. Täytyy itsekin ryhtyä tekemään näin. Selkeästi erilliset elementit määritellään omissa metodeissaan. Nämä voi helposti siirtää omiin luokkiinsa, jos rivimäärä kasvaa liian suureksi. Käyttöliittymä on myös eriytetty hyvin sovelluslogiikasta.

Puutteita ja kehityskohteita on jo valmiiksi hyvin dokumentoitu. Selkeitä puutteita, joita ei olisi jo mainittu, ei löytynyt. Yritin kuitenkin keksiä joitain ideoita ja ehdotuksia:

- Testaus vaikuttaa vielä hieman puutteellista, vaikka testikattavuus onkin hyvä. Reunatapauksia ei juurikaan käsitellä. Tähän on dokumentaation perusteella tulossa parannusta.

- Eri laskuoperaatiot voisi kenties säilyttää sovelluslogiikan puolella lueteltuna tyyppinä (*enum*). Tällä hetkellä käytössä on merkkijonot, jotka vastaavat suoraan ja ovat riippuvaisia käyttöliittymän tekstien sisällöstä. Jos käyttöliittymää haluaa tältä osin muokata, niin sovelluslogiikkaa joutuu korjaamaan useasta kohdasta.

- Metodi *updateAnswers* tekee monta asiaa. Se päivittää tulokset ja palauttaa käyttöliittymälle merkkijonon, joka näytetään käyttäjällä. Pitäisikö merkkijonon luominen jättää käyttöliittymän vastuulle?

- Metodi setUpperLimit vaikuttaa turhalta, koska sama asia tehdään jo konstruktorissa. Ehkä kyseisen metodin voisi poistaa?

**Comment by lauriap** [comment]
Kiitos palautteesta! Pohdin näitä, kun viimeistelen sovellusta.
